### ISSUE TITLE
client says map pins are appearing in the wrong places

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/insearchofthetruth-net#59]

**Comment by mikeyrayvon** [comment]
via client:
<img width="586" alt="screen shot 2017-11-25 at 11 22 30 am" src="https://user-images.githubusercontent.com/7727722/33232858-f6c4020a-d1d2-11e7-90b1-820c7ee19b1e.png">

**Comment by mixcas** [comment]
idk where are they getting their coordinates from but bamiyan coordinates on google maps are *34.8128069, 67.8213502* and they have *34.832063, 67.826758* which is enough difference to mislocate the pin. 

Let's recommend them to get the coordinates from google maps.
